import { Language } from './types';

export const CROPS = ['Rice', 'Wheat', 'Maize', 'Cotton', 'Sugarcane', 'Soybean'];
export const SOIL_TYPES = ['Alluvial', 'Black', 'Red', 'Laterite', 'Clay'];
export const SEASONS = ['Kharif', 'Rabi', 'Zaid'];

export const STATE_DISTRICT_MAP: Record<string, string[]> = {
  'Andhra Pradesh': ['Anantapur', 'Chittoor', 'East Godavari', 'Guntur', 'Krishna', 'Kurnool', 'Prakasam', 'Srikakulam', 'Sri Potti Sriramulu Nellore', 'Visakhapatnam', 'Vizianagaram', 'West Godavari', 'YSR District (Kadapa)'],
  'Arunachal Pradesh': ['Tawang', 'West Kameng', 'East Kameng', 'Papum Pare', 'Kurung Kumey', 'Kra Daadi', 'Lower Subansiri', 'Upper Subansiri', 'West Siang', 'East Siang', 'Siang', 'Upper Siang', 'Lower Siang', 'Lower Dibang Valley', 'Upper Dibang Valley', 'Anjaw', 'Lohit', 'Namsai', 'Changlang', 'Tirap', 'Longding'],
  'Assam': ['Baksa', 'Barpeta', 'Biswanath', 'Bongaigaon', 'Cachar', 'Charaideo', 'Chirang', 'Darrang', 'Dhemaji', 'Dhubri', 'Dibrugarh', 'Goalpara', 'Golaghat', 'Hailakandi', 'Hojai', 'Jorhat', 'Kamrup Metropolitan', 'Kamrup', 'Karbi Anglong', 'Karimganj', 'Kokrajhar', 'Lakhimpur', 'Majuli', 'Morigaon', 'Nagaon', 'Nalbari', 'Dima Hasao', 'Sivasagar', 'Sonitpur', 'South Salmara-Mankachar', 'Tinsukia', 'Udalguri', 'West Karbi Anglong'],
  'Bihar': ['Araria', 'Arwal', 'Aurangabad', 'Banka', 'Begusarai', 'Bhagalpur', 'Bhojpur', 'Buxar', 'Darbhanga', 'East Champaran', 'Gaya', 'Gopalganj', 'Jamui', 'Jehanabad', 'Kaimur', 'Katihar', 'Khagaria', 'Kishanganj', 'Lakhisarai', 'Madhepura', 'Madhubani', 'Munger', 'Muzaffarpur', 'Nalanda', 'Nawada', 'Patna', 'Purnia', 'Rohtas', 'Saharsa', 'Samastipur', 'Saran', 'Sheikhpura', 'Sheohar', 'Sitamarhi', 'Siwan', 'Supaul', 'Vaishali', 'West Champaran'],
  'Chhattisgarh': ['Balod', 'Baloda Bazar', 'Balrampur', 'Bastar', 'Bemetara', 'Bijapur', 'Bilaspur', 'Dantewada', 'Dhamtari', 'Durg', 'Gariaband', 'Janjgir-Champa', 'Jashpur', 'Kabirdham', 'Kanker', 'Kondagaon', 'Korba', 'Koriya', 'Mahasamund', 'Mungeli', 'Narayanpur', 'Raigarh', 'Raipur', 'Rajnandgaon', 'Sukma', 'Surajpur', 'Surguja'],
  'Goa': ['North Goa', 'South Goa'],
  'Gujarat': ['Ahmedabad', 'Amreli', 'Anand', 'Aravalli', 'Banaskantha', 'Bharuch', 'Bhavnagar', 'Botad', 'Chhota Udepur', 'Dahod', 'Dang', 'Devbhumi Dwarka', 'Gandhinagar', 'Gir Somnath', 'Jamnagar', 'Junagadh', 'Kheda', 'Kutch', 'Mahisagar', 'Mehsana', 'Morbi', 'Narmada', 'Navsari', 'Panchmahal', 'Patan', 'Porbandar', 'Rajkot', 'Sabarkantha', 'Surat', 'Surendranagar', 'Tapi', 'Vadodara', 'Valsad'],
  'Haryana': ['Ambala', 'Bhiwani', 'Charkhi Dadri', 'Faridabad', 'Fatehabad', 'Gurugram', 'Hisar', 'Jhajjar', 'Jind', 'Kaithal', 'Karnal', 'Kurukshetra', 'Mahendragarh', 'Nuh', 'Palwal', 'Panchkula', 'Panipat', 'Rewari', 'Rohtak', 'Sirsa', 'Sonipat', 'Yamunanagar'],
  'Himachal Pradesh': ['Bilaspur', 'Chamba', 'Hamirpur', 'Kangra', 'Kinnaur', 'Kullu', 'Lahaul and Spiti', 'Mandi', 'Shimla', 'Sirmaur', 'Solan', 'Una'],
  'Jharkhand': ['Bokaro', 'Chatra', 'Deoghar', 'Dhanbad', 'Dumka', 'East Singhbhum', 'Garhwa', 'Giridih', 'Godda', 'Gumla', 'Hazaribagh', 'Jamtara', 'Khunti', 'Koderma', 'Latehar', 'Lohardaga', 'Pakur', 'Palamu', 'Ramgarh', 'Ranchi', 'Sahibganj', 'Seraikela Kharsawan', 'Simdega', 'West Singhbhum'],
  'Karnataka': ['Bagalkot', 'Ballari', 'Belagavi', 'Bengaluru Rural', 'Bengaluru Urban', 'Bidar', 'Chamarajanagar', 'Chikkaballapur', 'Chikkamagaluru', 'Chitradurga', 'Dakshina Kannada', 'Davanagere', 'Dharwad', 'Gadag', 'Hassan', 'Haveri', 'Kalaburagi', 'Kodagu', 'Kolar', 'Koppal', 'Mandya', 'Mysuru', 'Raichur', 'Ramanagara', 'Shivamogga', 'Tumakuru', 'Udupi', 'Uttara Kannada', 'Vijayapura', 'Yadgir'],
  'Kerala': ['Alappuzha', 'Ernakulam', 'Idukki', 'Kannur', 'Kasaragod', 'Kollam', 'Kottayam', 'Kozhikode', 'Malappuram', 'Palakkad', 'Pathanamthitta', 'Thiruvananthapuram', 'Thrissur', 'Wayanad'],
  'Madhya Pradesh': ['Agar Malwa', 'Alirajpur', 'Anuppur', 'Ashoknagar', 'Balaghat', 'Barwani', 'Betul', 'Bhind', 'Bhopal', 'Burhanpur', 'Chhatarpur', 'Chhindwara', 'Damoh', 'Datia', 'Dewas', 'Dhar', 'Dindori', 'Guna', 'Gwalior', 'Harda', 'Hoshangabad', 'Indore', 'Jabalpur', 'Jhabua', 'Katni', 'Khandwa', 'Khargone', 'Mandla', 'Mandsaur', 'Morena', 'Narsinghpur', 'Neemuch', 'Panna', 'Raisen', 'Rajgarh', 'Ratlam', 'Rewa', 'Sagar', 'Satna', 'Sehore', 'Seoni', 'Shahdol', 'Shajapur', 'Sheopur', 'Shivpuri', 'Sidhi', 'Singrauli', 'Tikamgarh', 'Ujjain', 'Umaria', 'Vidisha'],
  'Maharashtra': ['Ahmednagar', 'Akola', 'Amravati', 'Aurangabad', 'Beed', 'Bhandara', 'Buldhana', 'Chandrapur', 'Dhule', 'Gadchiroli', 'Gondia', 'Hingoli', 'Jalgaon', 'Jalna', 'Kolhapur', 'Latur', 'Mumbai City', 'Mumbai Suburban', 'Nagpur', 'Nanded', 'Nandurbar', 'Nashik', 'Osmanabad', 'Palghar', 'Parbhani', 'Pune', 'Raigad', 'Ratnagiri', 'Sangli', 'Satara', 'Sindhudurg', 'Solapur', 'Thane', 'Wardha', 'Washim', 'Yavatmal'],
  'Manipur': ['Bishnupur', 'Chandel', 'Churachandpur', 'Imphal East', 'Imphal West', 'Jiribam', 'Kakching', 'Kamjong', 'Kangpokpi', 'Noney', 'Pherzawl', 'Senapati', 'Tamenglong', 'Tengnoupal', 'Thoubal', 'Ukhrul'],
  'Meghalaya': ['East Garo Hills', 'East Jaintia Hills', 'East Khasi Hills', 'North Garo Hills', 'Ri Bhoi', 'South Garo Hills', 'South West Garo Hills', 'South West Khasi Hills', 'West Garo Hills', 'West Jaintia Hills', 'West Khasi Hills'],
  'Mizoram': ['Aizawl', 'Champhai', 'Kolasib', 'Lawngtlai', 'Lunglei', 'Mamit', 'Saiha', 'Serchhip'],
  'Nagaland': ['Dimapur', 'Kiphire', 'Kohima', 'Longleng', 'Mokokchung', 'Mon', 'Peren', 'Phek', 'Tuensang', 'Wokha', 'Zunheboto'],
  'Odisha': ['Angul', 'Balangir', 'Balasore', 'Bargarh', 'Bhadrak', 'Boudh', 'Cuttack', 'Deogarh', 'Dhenkanal', 'Gajapati', 'Ganjam', 'Jagatsinghpur', 'Jajpur', 'Jharsuguda', 'Kalahandi', 'Kandhamal', 'Kendrapara', 'Kendujhar', 'Khordha', 'Koraput', 'Malkangiri', 'Mayurbhanj', 'Nabarangpur', 'Nayagarh', 'Nuapada', 'Puri', 'Rayagada', 'Sambalpur', 'Subarnapur', 'Sundargarh'],
  'Punjab': ['Amritsar', 'Barnala', 'Bathinda', 'Faridkot', 'Fatehgarh Sahib', 'Fazilka', 'Ferozepur', 'Gurdaspur', 'Hoshiarpur', 'Jalandhar', 'Kapurthala', 'Ludhiana', 'Mansa', 'Moga', 'Muktsar', 'Pathankot', 'Patiala', 'Rupnagar', 'Sahibzada Ajit Singh Nagar', 'Sangrur', 'Shahid Bhagat Singh Nagar', 'Sri Muktsar Sahib', 'Tarn Taran'],
  'Rajasthan': ['Ajmer', 'Alwar', 'Banswara', 'Baran', 'Barmer', 'Bharatpur', 'Bhilwara', 'Bikaner', 'Bundi', 'Chittorgarh', 'Churu', 'Dausa', 'Dholpur', 'Dungarpur', 'Hanumangarh', 'Jaipur', 'Jaisalmer', 'Jalore', 'Jhalawar', 'Jhunjhunu', 'Jodhpur', 'Karauli', 'Kota', 'Nagaur', 'Pali', 'Pratapgarh', 'Rajsamand', 'Sawai Madhopur', 'Sikar', 'Sirohi', 'Sri Ganganagar', 'Tonk', 'Udaipur'],
  'Sikkim': ['East Sikkim', 'North Sikkim', 'South Sikkim', 'West Sikkim'],
  'Tamil Nadu': ['Ariyalur', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri', 'Dindigul', 'Erode', 'Kanchipuram', 'Kanyakumari', 'Karur', 'Krishnagiri', 'Madurai', 'Nagapattinam', 'Namakkal', 'Nilgiris', 'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Salem', 'Sivaganga', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore', 'Viluppuram', 'Virudhunagar'],
  'Telangana': ['Adilabad', 'Bhadradri Kothagudem', 'Hyderabad', 'Jagtial', 'Jangaon', 'Jayashankar Bhupalpally', 'Jogulamba Gadwal', 'Kamareddy', 'Karimnagar', 'Khammam', 'Kumuram Bheem Asifabad', 'Mahabubabad', 'Mahabubnagar', 'Mancherial', 'Medak', 'Medchal-Malkajgiri', 'Nagarkurnool', 'Nalgonda', 'Nirmal', 'Nizamabad', 'Peddapalli', 'Rajanna Sircilla', 'Rangareddy', 'Sangareddy', 'Siddipet', 'Suryapet', 'Vikarabad', 'Wanaparthy', 'Warangal Rural', 'Warangal Urban', 'Yadadri Bhuvanagiri'],
  'Tripura': ['Dhalai', 'Gomati', 'Khowai', 'North Tripura', 'Sepahijala', 'South Tripura', 'Unakoti', 'West Tripura'],
  'Uttar Pradesh': ['Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', 'Chitrakoot', 'Deoria', 'Etah', 'Etawah', 'Faizabad', 'Farrukhabad', 'Fatehpur', 'Firozabad', 'Gautam Buddha Nagar', 'Ghaziabad', 'Ghazipur', 'Gonda', 'Gorakhpur', 'Hamirpur', 'Hapur', 'Hardoi', 'Hathras', 'Jalaun', 'Jaunpur', 'Jhansi', 'Kannauj', 'Kanpur Dehat', 'Kanpur Nagar', 'Kasganj', 'Kaushambi', 'Kheri', 'Kushinagar', 'Lakhimpur Kheri', 'Lalitpur', 'Lucknow', 'Maharajganj', 'Mahoba', 'Mainpuri', 'Mathura', 'Mau', 'Meerut', 'Mirzapur', 'Moradabad', 'Muzaffarnagar', 'Pilibhit', 'Pratapgarh', 'Prayagraj', 'Rae Bareli', 'Rampur', 'Saharanpur', 'Sambhal', 'Sant Kabir Nagar', 'Shahjahanpur', 'Shamli', 'Shravasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
  'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri Garhwal', 'Udham Singh Nagar', 'Uttarkashi'],
  'West Bengal': ['Alipurduar', 'Bankura', 'Birbhum', 'Cooch Behar', 'Dakshin Dinajpur', 'Darjeeling', 'Hooghly', 'Howrah', 'Jalpaiguri', 'Jhargram', 'Kalimpong', 'Kolkata', 'Malda', 'Murshidabad', 'Nadia', 'North 24 Parganas', 'Paschim Bardhaman', 'Paschim Medinipur', 'Purba Bardhaman', 'Purba Medinipur', 'Purulia', 'South 24 Parganas', 'Uttar Dinajpur'],
  'Andaman and Nicobar Islands': ['Nicobar', 'North and Middle Andaman', 'South Andaman'],
  'Chandigarh': ['Chandigarh'],
  'Dadra and Nagar Haveli and Daman and Diu': ['Dadra and Nagar Haveli', 'Daman', 'Diu'],
  'Delhi': ['Central Delhi', 'East Delhi', 'New Delhi', 'North Delhi', 'North East Delhi', 'North West Delhi', 'Shahdara', 'South Delhi', 'South East Delhi', 'South West Delhi', 'West Delhi'],
  'Jammu and Kashmir': ['Anantnag', 'Bandipora', 'Baramulla', 'Budgam', 'Doda', 'Ganderbal', 'Jammu', 'Kathua', 'Kishtwar', 'Kulgam', 'Kupwara', 'Poonch', 'Pulwama', 'Rajouri', 'Ramban', 'Reasi', 'Samba', 'Shopian', 'Srinagar', 'Udhampur'],
  'Ladakh': ['Kargil', 'Leh'],
  'Lakshadweep': ['Lakshadweep'],
  'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam']
};

export const STATES = Object.keys(STATE_DISTRICT_MAP).sort();
export const DISTRICTS = STATE_DISTRICT_MAP['Andhra Pradesh']; // Default for starting state

export const TRANSLATIONS = {
  [Language.ENGLISH]: {
    appTitle: "Agri-Yield Assistant",
    dashboard: "Dashboard",
    predict: "Predict Yield",
    assistant: "Ask Assistant",
    weather: "Weather",
    history: "Farm History",
    risk: "Risk Analysis",
    welcome: "Welcome, Farmer",
    actions: "Quick Actions",
    recentAlerts: "Recent Alerts",
    yieldResult: "Estimated Yield",
    confidence: "Accuracy",
    savings: "Potential Savings",
    recommendation: "Recommendation",
    submit: "Calculate",
    listening: "Listening...",
    speak: "Tap to Speak",
    loading: "Analyzing...",
  },
  [Language.HINDI]: {
    appTitle: "कृषि उपज सहायक",
    dashboard: "डैशबोर्ड",
    predict: "उपज अनुमान",
    assistant: "सहायक से पूछें",
    weather: "मौसम",
    history: "खेत का इतिहास",
    risk: "जोखिम विश्लेषण",
    welcome: "स्वागत है, किसान भाई",
    actions: "त्वरित कार्य",
    recentAlerts: "हालिया चेतावनी",
    yieldResult: "अनुमानित उपज",
    confidence: "सटीकता",
    savings: "संभावित बचत",
    recommendation: "सुझाव",
    submit: "गणना करें",
    listening: "सुन रहा हूँ...",
    speak: "बोलने के लिए दबाएं",
    loading: "विश्लेषण कर रहा है...",
  },
  [Language.MARATHI]: {
    appTitle: "कृषी उत्पन्न सहाय्यक",
    dashboard: "डॅशबोर्ड",
    predict: "उत्पन्न अंदाज",
    assistant: "सहायक",
    weather: "हवामान",
    history: "शेतीचा इतिहास",
    risk: "जोखीम विश्लेषण",
    welcome: "स्वागत आहे, शेतकरी दादा",
    actions: "जलद क्रिया",
    recentAlerts: "अलीकडील सूचना",
    yieldResult: "अंदाजित उत्पन्न",
    confidence: "अचूकता",
    savings: "संभाव्य बचत",
    recommendation: "शिफारस",
    submit: "गणना करा",
    listening: "ऐकत आहे...",
    speak: "बोलण्यासाठी दाबा",
    loading: "विश्लेषण करत आहे...",
  },
  [Language.TELUGU]: {
    appTitle: "వ్యవసాయ దిగుబడి సహాయకుడు",
    dashboard: "డ్యాష్‌బోర్డ్",
    predict: "దిగుబడి అంచనా",
    assistant: "సహాయకుడిని అడగండి",
    weather: "వాతావరణం",
    history: "పంట చరిత్ర",
    risk: "ప్రమాద విశ్లేషణ",
    welcome: "స్వాగతం, రైతు",
    actions: "త్వరిత చర్యలు",
    recentAlerts: "ఇటీవలి హెచ్చరికలు",
    yieldResult: "అంచనా వేసిన దిగుబడి",
    confidence: "ఖచ్చితత్వం",
    savings: "ఆదా",
    recommendation: "సిఫార్సు",
    submit: "లెక్కించు",
    listening: "వింటున్నాను...",
    speak: "మాట్లాడటానికి నొక్కండి",
    loading: "విశ్లేషిస్తోంది...",
  },
  [Language.TAMIL]: {
    appTitle: "விவசாய விளைச்சல் உதவியாளர்",
    dashboard: "முகப்பு",
    predict: "விளைச்சல் கணிப்பு",
    assistant: "உதவியாளர்",
    weather: "வானிலை",
    history: "பண்ணை வரலாறு",
    risk: "ஆபத்து பகுப்பாய்வு",
    welcome: "வணக்கம், விவசாயி",
    actions: "விரะவான செயல்கள்",
    recentAlerts: "சமீபத்திய எச்சரிக்கைகள்",
    yieldResult: "மதிப்பிடப்பட்ட விளைச்சல்",
    confidence: "துல்லியம்",
    savings: "சேமிப்பு",
    recommendation: "பரிந்துரை",
    submit: "கணக்கிடு",
    listening: "கேட்கிறது...",
    speak: "பேச தட்டவும்",
    loading: "பகுப்பாய்வு...",
  },
  [Language.GUJARATI]: {
    appTitle: "કૃષિ ઉપજ સહાયક",
    dashboard: "ડેશબોર્ડ",
    predict: "ઉપજની આગાહી",
    assistant: "સહાયકને પૂછો",
    weather: "હવામાન",
    history: "ખેતરનો ઇતિહાસ",
    risk: "જોખમ વિશ્લેષણ",
    welcome: "સ્વાગત છે, ખેડૂત મિત્ર",
    actions: "ઝડપી ક્રિયાઓ",
    recentAlerts: "તાજેતરની ચેતવણીઓ",
    yieldResult: "અંદાજિત ઉપજ",
    confidence: "ચોકસાઈ",
    savings: "સંભવિત બચત",
    recommendation: "ભલામણ",
    submit: "ગણતરી કરો",
    listening: "સાંભળી રહ્યું છે...",
    speak: "બોલવા માટે ટેપ કરો",
    loading: "વિશ્લેષણ કરી રહ્યું છે...",
  },
  [Language.BANGLA]: {
    appTitle: "কৃষি ফলন সহায়ক",
    dashboard: "ড্যাশবোর্ড",
    predict: "ফলন পূর্বাভাস",
    assistant: "সহায়কারী",
    weather: "আবহাওয়া",
    history: "খামারের ইতিহাস",
    risk: "ঝুঁকি বিশ্লেষণ",
    welcome: "স্বাগতম, কৃষক বন্ধু",
    actions: "দ্রুত পদক্ষেপ",
    recentAlerts: "সাম্প্রতিক সতর্কতা",
    yieldResult: "আনুমানিক ফলন",
    confidence: "নির্ভুলতা",
    savings: "সম্ভাব্য সঞ্চয়",
    recommendation: "সুপারিশ",
    submit: "গণনা করুন",
    listening: "শুনছে...",
    speak: "কথা বলতে ট্যাপ করুন",
    loading: "বিশ্লেষণ করা হচ্ছে...",
  },
  [Language.URDU]: {
    appTitle: "زرعی پیداوار معاون",
    dashboard: "ڈیش بورڈ",
    predict: "پیداوار کی پیشین گوئی",
    assistant: "معاون سے پوچھیں",
    weather: "موسم",
    history: "فارم کی تاریخ",
    risk: "خطرات کا تجزیہ",
    welcome: "خوش آمدید، کسان بھائی",
    actions: "فوری اقدامات",
    recentAlerts: "حالیہ انتباہات",
    yieldResult: "متوقع پیداوار",
    confidence: "درستگی",
    savings: "ممکنہ بچت",
    recommendation: "تجویز",
    submit: "حساب لگائیں",
    listening: "سن رہا ہے...",
    speak: "بولنے کے لیے ٹیپ کریں",
    loading: "تجزیہ کر رہا है...",
  }
};